server {
    listen 80;
    server_name localhost; # Для локальной разработки. На сервере тут будет твой домен

    location / {
        # Перенаправляем трафик на наш сервис gateway внутри сети Docker
        proxy_pass http://gateway:8080;
        
        # Передаем правильные заголовки, чтобы Gateway видел реальный IP пользователя, а не IP Nginx'а
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}